In [1]:
import pandas as pd

# Define data structure for ratings dictionary.

# Primary dictionary key is TeamID, secondary key is beginning (temporary) rating which is set at zero, 
# and each update will be marked with an ID of the season + daynum.

df_teams = pd.read_csv('Teams.csv')

Ratings = {}

for i in range(len(df_teams.index)):
    Ratings[df_teams.iloc[i]['Team_Id']] = {'temp':1500.0}

In [2]:
# Define rating and updating related functions

# We only need W & L Teams, season & daynum.
def update_rating(WTeam,LTeam,Season,Daynum):
    
    # Stamp current season & daynum with temp ranking.
    Ratings[WTeam][str(Season) + str(Daynum)] = Ratings[WTeam]['temp']
    #print 'WTeam ELO Before: ', Ratings[WTeam]['temp']
    Ratings[LTeam][str(Season) + str(Daynum)] = Ratings[LTeam]['temp']
    #print 'LTeam ELO Before: ', Ratings[LTeam]['temp']

    # Calculate new rankings, using k = 20.
    new_rankings = ELO(WTeam,LTeam,20)
    
    # Update temporary ranking.
    Ratings[WTeam]['temp'] = new_rankings[0]
    #print 'WTeam ELO After: ', Ratings[WTeam]['temp']
    Ratings[LTeam]['temp'] = new_rankings[1]
    #print 'LTeam ELO After: ', Ratings[LTeam]['temp']

    
# Returns a tuple of updated ELO score based on two current rankings.
def ELO(WTeam,LTeam,k):
    trans_WELO = 10**((Ratings[WTeam]['temp'])/(400.0))
    trans_LELO = 10**((Ratings[LTeam]['temp'])/(400.0))
    
    expected_Wscore = trans_WELO / (trans_WELO + trans_LELO)
    #print 'Expected WScore: ', expected_Wscore
    expected_Lscore = trans_LELO / (trans_WELO + trans_LELO)
    #print 'Expected LScore: ', expected_Lscore
    
    new_WELO = (Ratings[WTeam]['temp']) + k*(1.0 - expected_Wscore)
    #print 'Calculated WTeam ELO: ', new_WELO
    new_LELO = (Ratings[LTeam]['temp']) + k*(0.0 - expected_Lscore)
    #print 'Calculated LTeam ELO: ', new_LELO

    return (new_WELO, new_LELO)

In [3]:
# Read csv files.
df1 = pd.read_csv('RegularSeasonCompactResults.csv')
df2 = pd.read_csv('TourneyCompactResults.csv')

# Merge data frames and sort by year and day number.

df = pd.concat([df1,df2], ignore_index=True)
df.sort_values(by = ['Season','Daynum'], ascending=True)

        Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0         1985      20   1228      81   1328      64    N      0
1         1985      25   1106      77   1354      70    H      0
2         1985      25   1112      63   1223      56    H      0
3         1985      25   1165      70   1432      54    H      0
4         1985      25   1192      86   1447      74    H      0
5         1985      25   1218      79   1337      78    H      0
6         1985      25   1228      64   1226      44    N      0
7         1985      25   1242      58   1268      56    N      0
8         1985      25   1260      98   1133      80    H      0
9         1985      25   1305      97   1424      89    H      0
10        1985      25   1307     103   1288      71    H      0
11        1985      25   1344      75   1438      71    N      0
12        1985      25   1374      91   1411      72    H      0
13        1985      25   1412      70   1397      65    N      0
14        1985      25   1417      87   1225      58    H      0
15        1985      26   1116      65   1368      62    H      0
16        1985      26   1120      92   1391      50    H      0
17        1985      26   1135      65   1306      60    A      0
18        1985      26   1143      58   1388      53    H      0
19        1985      26   1153      50   1184      48    H      0
20        1985      26   1165      47   1159      40    A      0
21        1985      26   1171      55   1216      52    H      0
22        1985      26   1173      76   1134      56    H      0
23        1985      26   1177      59   1296      58    H      0
24        1985      26   1193      79   1265      76    A      0
25        1985      26   1196     106   1416      55    H      0
26        1985      26   1206      95   1137      77    H      0
27        1985      26   1210      79   1149      66    H      0
28        1985      26   1211      64   1102      59    A      0
29        1985      26   1234      76   1114      47    H      0
...        ...     ...    ...     ...    ...     ...  ...    ...
147309    2016     138   1211      82   1428      59    N      0
147310    2016     138   1231      73   1246      67    N      0
147311    2016     138   1235      78   1114      61    N      0
147312    2016     138   1242      73   1163      61    N      0
147313    2016     138   1274      65   1455      57    N      0
147314    2016     138   1314      85   1344      66    N      0
147315    2016     138   1438      77   1139      69    N      0
147316    2016     139   1268      73   1218      60    N      0
147317    2016     139   1323      76   1372      75    N      0
147318    2016     139   1328      85   1433      81    N      0
147319    2016     139   1332      69   1386      64    N      0
147320    2016     139   1393      75   1292      50    N      0
147321    2016     139   1401      92   1320      88    N      2
147322    2016     139   1437      87   1234      68    N      0
147323    2016     139   1458      66   1462      63    N      0
147324    2016     143   1242      79   1268      63    N      0
147325    2016     143   1328      77   1401      63    N      0
147326    2016     143   1332      82   1181      68    N      0
147327    2016     143   1437      92   1274      69    N      0
147328    2016     144   1314     101   1231      86    N      0
147329    2016     144   1323      61   1458      56    N      0
147330    2016     144   1393      63   1211      60    N      0
147331    2016     144   1438      84   1235      71    N      0
147332    2016     145   1328      80   1332      68    N      0
147333    2016     145   1437      64   1242      59    N      0
147334    2016     146   1314      88   1323      74    N      0
147335    2016     146   1393      68   1438      62    N      0
147336    2016     152   1314      83   1393      66    N      0
147337    2016     152   1437      95   1328      51    N      0
147338    2016     154   1437      77   1314      74    N      0

[147339 rows x 8 columns]

In [4]:
years = range(2003,2017)    

for year in years:
    # Run update with k = 20
    for i in range(len(df.index)):
        if df.iloc[i]['Season'] == year:
            #print df.iloc[i]['Daynum'], df.iloc[i]['Wteam'], df.iloc[i]['Lteam']
            update_rating(df.iloc[i]['Wteam'],df.iloc[i]['Lteam'],df.iloc[i]['Season'],df.iloc[i]['Daynum'])

In [5]:
#df_duke=pd.DataFrame(data= list(Ratings[1181].values()), index=(Ratings[1181].keys()), columns= ['ELO'])
#df_duke.to_csv('duke_new.csv')

In [6]:
(Ratings[1181])

{'2003101': 1608.5004536224374,
 '2003103': 1598.4390520379682,
 '2003107': 1606.97865287578,
 '2003110': 1616.5254263409029,
 '2003114': 1624.6185350666976,
 '2003118': 1631.5377310095212,
 '2003122': 1617.8420202699692,
 '2003125': 1624.6782455070559,
 '2003130': 1611.54808625088,
 '2003131': 1618.501164004643,
 '2003132': 1626.2040533424583,
 '2003136': 1634.5025313187962,
 '2003138': 1642.0612072641245,
 '2003143': 1652.006581178288,
 '200319': 1500.0,
 '200321': 1510.0,
 '200326': 1519.71225631668,
 '200329': 1528.8673697795948,
 '200333': 1538.0377083091357,
 '200343': 1545.6321859539926,
 '200355': 1553.2690607496,
 '200359': 1563.0359642062124,
 '200362': 1571.5326009307182,
 '200365': 1581.7414177648325,
 '200369': 1591.1434521851004,
 '200372': 1601.0109699457705,
 '200375': 1609.6950514800346,
 '200379': 1597.9591082166835,
 '200382': 1586.2867207759086,
 '200387': 1594.6379070726946,
 '200390': 1604.784231637819,
 '200393': 1592.2366299119292,
 '200397': 1600.1358891265447,
 '2004100': 1759.3877505935297,
 '2004104': 1763.6201861114587,
 '2004107': 1750.2287587850847,
 '2004111': 1737.8437595374262,
 '2004115': 1744.0288855128993,
 '2004118': 1748.7963065933018,
 '2004121': 1753.8842225812907,
 '2004124': 1739.893810291631,
 '2004130': 1746.6791749866168,
 '2004131': 1751.8777621380566,
 '2004132': 1758.7362388134727,
 '2004136': 1745.3224938938154,
 '2004138': 1748.9612096409949,
 '2004144': 1755.8383020943988,
 '2004146': 1765.3347874832587,
 '2004152': 1774.0926716278611,
 '200419': 1642.1170806822138,
 '200424': 1649.4076120355442,
 '200425': 1654.4375815815463,
 '200426': 1659.5251103954859,
 '200430': 1647.526549961269,
 '200433': 1656.5805630641203,
 '200441': 1662.6301723966342,
 '200444': 1667.8649749019162,
 '200447': 1674.4967729768107,
 '200456': 1684.4883349683978,
 '200461': 1689.2287770207224,
 '200464': 1695.1176347358964,
 '200469': 1701.8159013696427,
 '200473': 1707.9030416209634,
 '200475': 1715.2076772385283,
 '200479': 1724.551647972172,
 '200482': 1731.635852339624,
 '200487': 1737.2425157396674,
 '200489': 1742.74045728908,
 '200494': 1749.299733836595,
 '200497': 1755.319295279512,
 '2005100': 1812.8529365859038,
 '2005103': 1820.4672742600462,
 '2005108': 1806.3702820191345,
 '2005111': 1789.87945567214,
 '2005114': 1799.621661800467,
 '2005117': 1806.4313149925872,
 '2005122': 1808.884331407171,
 '2005125': 1812.5159471295817,
 '2005130': 1801.0428249875658,
 '2005131': 1805.1550775783203,
 '2005132': 1811.2721527384854,
 '2005137': 1818.2332177276737,
 '2005139': 1821.1853047022805,
 '2005144': 1828.4531308159835,
 '200519': 1763.6144926111303,
 '200521': 1765.7460427847993,
 '200526': 1770.3517358751405,
 '200529': 1772.3685505373612,
 '200533': 1778.8831166964405,
 '200541': 1782.865572036684,
 '200543': 1786.7639811403294,
 '200547': 1792.789096598011,
 '200562': 1799.7093035002395,
 '200565': 1803.146628525459,
 '200568': 1807.9932258204046,
 '200573': 1811.9175846913236,
 '200576': 1817.454745583942,
 '200579': 1821.8690014796146,
 '200582': 1825.3647243433365,
 '200586': 1828.6818686626652,
 '200590': 1814.3253445265166,
 '200593': 1817.93934595754,
 '200596': 1805.9996197488165,
 '2006103': 1896.4670444314409,
 '2006106': 1900.6730825897703,
 '2006111': 1905.3271281496984,
 '2006114': 1908.0722626815846,
 '2006117': 1911.1468683931305,
 '2006121': 1914.1311028377959,
 '2006124': 1896.8571084286202,
 '2006130': 1885.0555137789304,
 '2006131': 1888.0792890029466,
 '2006132': 1893.1496764277397,
 '2006136': 1900.8116646911003,
 '2006138': 1902.2417921108452,
 '200614': 1815.583437907988,
 '2006143': 1908.3554113805897,
 '200616': 1820.7381288156596,
 '200619': 1824.6890927042132,
 '200623': 1829.1153029560367,
 '200625': 1833.6800653481318,
 '200630': 1839.4681143404287,
 '200634': 1843.533354077925,
 '200637': 1846.7374232465725,
 '200640': 1850.9971541811303,
 '200648': 1857.8546854026938,
 '200651': 1860.292159602867,
 '200661': 1862.1600551901242,
 '200663': 1864.0635011546733,
 '200669': 1868.3446487041253,
 '200672': 1876.0710245462014,
 '200675': 1880.5524537528447,
 '200679': 1883.8005651478481,
 '200682': 1889.7012991320894,
 '200687': 1873.0250230920221,
 '200689': 1875.639768046956,
 '200693': 1878.9792965333263,
 '200696': 1885.959338516935,
 '200699': 1888.7760469960126,
 '2007100': 1879.519593958276,
 '2007104': 1869.1971286800676,
 '2007107': 1854.3644001486316,
 '2007111': 1862.9951032724082,
 '2007115': 1867.967241589883,
 '2007118': 1872.7340016467342,
 '2007121': 1875.4802870429198,
 '2007125': 1861.8035927113217,
 '2007129': 1851.4692105999213,
 '200713': 1894.3650085122626,
 '2007136': 1836.533684691111,
 '200714': 1895.1101884460954,
 '200717': 1897.6710507493578,
 '200721': 1898.5873366280173,
 '200722': 1903.1724588953064,
 '200726': 1887.8351632048686,
 '200729': 1891.076022544626,
 '200733': 1895.1215079367678,
 '200737': 1899.6103117239113,
 '200740': 1902.9387883582506,
 '200750': 1907.4178516959182,
 '200752': 1911.322441545089,
 '200762': 1919.0031662924146,
 '200764': 1919.3970940592926,
 '200768': 1922.031943241776,
 '200772': 1904.5880349413192,
 '200776': 1887.9877494380514,
 '200780': 1890.7117197858342,
 '200782': 1894.8357625986903,
 '200787': 1899.6635491979894,
 '200790': 1904.582423108882,
 '200794': 1911.5452247158164,
 '200797': 1895.071962812873,
 '2008100': 1916.7624912927986,
 '2008104': 1922.4534716312276,
 '2008107': 1906.4248686441501,
 '2008110': 1889.8038891902445,
 '2008114': 1892.2266161298805,
 '2008117': 1895.883222983878,
 '2008121': 1900.0308356248754,
 '2008124': 1903.8420084048362,
 '2008130': 1895.3043457891583,
 '2008131': 1899.4867673704462,
 '2008136': 1885.4781980197672,
 '2008138': 1889.0703885262526,
 '200814': 1830.1676177412576,
 '200815': 1831.9775622921532,
 '200816': 1840.844360750612,
 '200820': 1848.2220832720693,
 '200822': 1850.4928782337665,
 '200826': 1859.803072295748,
 '200833': 1865.2644501415407,
 '20084': 1823.010271760884,
 '200842': 1869.2174011159598,
 '200845': 1871.8063398910604,
 '200862': 1861.7561976420423,
 '200865': 1863.5504877515666,
 '200869': 1866.4112637601672,
 '20087': 1825.705739753216,
 '200872': 1871.65863083704,
 '200875': 1876.5699204296495,
 '200880': 1882.3962266786054,
 '200883': 1886.6291516969402,
 '200887': 1892.3339216277282,
 '200889': 1897.3539223927123,
 '200893': 1900.710648678874,
 '200896': 1911.844438581122,
 '2009100': 1913.738840956283,
 '2009104': 1906.1582838387785,
 '2009108': 1891.0516700512123,
 '2009111': 1893.4891392147438,
 '2009114': 1899.9008888137246,
 '2009117': 1905.647434719672,
 '2009120': 1910.5533201915662,
 '2009125': 1916.6291361067724,
 '200913': 1879.2639770001438,
 '2009130': 1908.9993355885426,
 '2009131': 1914.2066475933339,
 '2009132': 1919.6035552439137,
 '2009136': 1926.0455478025785,
 '2009138': 1927.8941050165117,
 '2009143': 1935.3133726359872,
 '200917': 1882.7668026347399,
 '200918': 1888.505723137936,
 '200920': 1891.665195952679,
 '200925': 1893.125269773968,
 '200929': 1894.735980573331,
 '200933': 1900.4238079374777,
 '200944': 1883.3526554233733,
 '200947': 1884.5724966206587,
 '200958': 1893.8369100139384,
 '200962': 1895.4619367395755,
 '200965': 1900.1812651826365,
 '200968': 1907.2125218192339,
 '20097': 1876.0963701039072,
 '200972': 1912.51880453557,
 '200975': 1915.9498142924617,
 '200978': 1925.5552344433347,
 '20098': 1876.9493783623568,
 '200982': 1929.0898714912726,
 '200986': 1933.8036247673783,
 '200990': 1919.2385472906938,
 '200993': 1922.0725420715003,
 '200996': 1909.0058944938874,
 '2010100': 1933.258032830791,
 '2010103': 1942.154321597469,
 '2010107': 1947.4977896724847,
 '201011': 1923.3546509419275,
 '2010111': 1951.2549256533248,
 '2010115': 1956.9142774487068,
 '2010118': 1960.2751849588242,
 '2010121': 1962.8110586719279,
 '2010124': 1948.499565772465,
 '2010130': 1956.0359458436442,
 '2010131': 1958.5814377679208,
 '2010132': 1962.2649903757535,
 '2010137': 1966.1990653004455,
 '2010139': 1966.8342083943403,
 '201014': 1924.0621834933543,
 '2010144': 1972.040181525417,
 '2010146': 1979.722908534751,
 '201015': 1924.6001928035205,
 '2010152': 1985.2188078991198,
 '2010154': 1993.3728591866077,
 '201019': 1926.647133113759,
 '201023': 1927.7330947543446,
 '201025': 1932.7086748201148,
 '201030': 1941.9989630115526,
 '201033': 1928.4827991827963,
 '201043': 1931.496644925412,
 '201047': 1932.1039642863534,
 '201057': 1939.6313757510786,
 '201059': 1940.8541955999378,
 '201062': 1941.5209000980751,
 '201065': 1947.223870371563,
 '201068': 1949.6288709918642,
 '201072': 1932.5747166383824,
 '201076': 1936.5162021410222,
 '201079': 1942.4375592884496,
 '201082': 1925.9556390106545,
 '201086': 1932.2815968803084,
 '201089': 1938.4837532529234,
 '201094': 1925.2773489054293,
 '201096': 1929.3426243164583,
 '2011100': 2023.621322970535,
 '2011104': 2029.2941452168045,
 '2011107': 2032.0491384608488,
 '2011111': 2033.808322349998,
 '2011114': 2035.8572575819169,
 '2011117': 2040.6705634574791,
 '2011121': 2024.3922785541333,
 '2011124': 2028.1478060178415,
 '201113': 2000.7550281935605,
 '2011130': 2014.4905922709243,
 '2011131': 2018.3576387770163,
 '2011132': 2022.68360586583,
 '2011137': 2029.8099211717922,
 '2011139': 2030.4365532553861,
 '2011143': 2033.4556027430317,
 '201115': 2001.6534959329938,
 '201118': 2003.007058690676,
 '201121': 2003.3522743129236,
 '201122': 2008.4271952293277,
 '201126': 2014.277596023828,
 '201130': 2016.0371890022614,
 '201133': 2023.002494286059,
 '201137': 2028.9122793792437,
 '201140': 2030.4251647022968,
 '201149': 2032.086079131016,
 '201158': 2032.375309150153,
 '201162': 2032.6320770680823,
 '201165': 2035.4371565797378,
 '201169': 2038.423118964959,
 '201172': 2042.1694683918402,
 '201175': 2025.592570986839,
 '201179': 2027.5499117848146,
 '201182': 2029.9592246163954,
 '201187': 2031.9793354833744,
 '201190': 2034.6870688269441,
 '201193': 2016.956437139213,
 '201196': 2021.2874977181698,
 '2012100': 2009.0499644284002,
 '2012103': 2017.2561036563748,
 '2012108': 2020.7047971683814,
 '201211': 2018.2294338548056,
 '2012111': 2023.7031804452467,
 '2012115': 2025.3157108565372,
 '2012117': 2030.3529080851742,
 '201212': 2020.2088643069649,
 '2012120': 2033.4575255134066,
 '2012124': 2034.8850090232816,
 '2012130': 2022.886502702279,
 '2012131': 2025.9024920223922,
 '2012137': 2011.0385573326585,
 '201215': 2020.513026891411,
 '201218': 2025.0325375562677,
 '201221': 2026.3385816762177,
 '201222': 2030.4170322350901,
 '201223': 2033.6180281814345,
 '201229': 2043.7268193825062,
 '201237': 2031.5867056734016,
 '201240': 2033.1407913862326,
 '201249': 2037.108398855096,
 '201260': 2037.3496480202032,
 '201262': 2038.3572224291595,
 '201265': 2038.86272361302,
 '201268': 2023.361503576768,
 '201273': 2024.971814765157,
 '201276': 2027.946297422042,
 '201280': 2030.8716845920121,
 '201282': 2032.3860223398397,
 '201286': 2016.4760792362968,
 '201289': 2019.9337172018688,
 '201294': 2022.6342564014196,
 '201297': 2026.0296135353876,
 '2013100': 2029.338802085565,
 '2013103': 2036.201867748278,
 '2013108': 2019.49969140061,
 '2013111': 2021.556190856604,
 '2013115': 2023.1776646375877,
 '2013117': 2007.0037768051936,
 '2013120': 2012.9841496323302,
 '2013124': 2015.313940743366,
 '201313': 2005.1485602101666,
 '2013130': 2023.2137916464053,
 '2013137': 2006.6007985512574,
 '2013139': 2007.604278310569,
 '2013144': 2012.8876077821844,
 '2013146': 2020.5767856977777,
 '201317': 2005.5748537112263,
 '201318': 2008.8354771670402,
 '201319': 2013.6945792238885,
 '201323': 2021.5745731062227,
 '201326': 2030.5676652527566,
 '201333': 2031.452171991777,
 '20134': 1992.2840195662038,
 '201344': 2036.545172829838,
 '201345': 2037.2029402859266,
 '201354': 2037.6876318678674,
 '201358': 2038.346258116351,
 '201361': 2040.2021667315664,
 '201364': 2041.5161386820962,
 '201368': 2043.9154286255812,
 '201373': 2027.9374767625982,
 '201379': 2029.4938300607912,
 '20138': 1993.4870197134367,
 '201382': 2013.5327674536925,
 '201386': 2017.3638859538305,
 '201389': 2018.9701100241132,
 '201394': 2023.7436031916143,
 '201397': 2027.9246739741793,
 '2014103': 2003.363736741429,
 '2014106': 2007.0617800410662,
 '2014108': 2009.1897545378058,
 '201411': 2003.9676386965325,
 '2014110': 1996.8587119748984,
 '2014113': 2008.1445210709016,
 '2014121': 2009.6631567911807,
 '2014124': 1991.6356067161091,
 '2014130': 2000.5916868493398,
 '2014131': 2003.9385325208757,
 '2014132': 2009.1708104721156,
 '2014137': 1995.879189677621,
 '201414': 2004.5722038930378,
 '201415': 2005.301856250498,
 '201420': 2006.7057422594755,
 '201423': 2007.785619417532,
 '201425': 2011.7825090927945,
 '201429': 1997.8818094419416,
 '20144': 2010.2620364396644,
 '201442': 2004.905736480818,
 '201445': 2005.4512715397395,
 '201454': 2010.3314217198142,
 '201457': 2011.0485434946927,
 '201461': 2011.8781175797158,
 '201464': 1997.192892976953,
 '201468': 1999.3437067373561,
 '201470': 1981.7884201376721,
 '201475': 1986.7022444720624,
 '201479': 1991.4217895345992,
 '20148': 2013.1130985754398,
 '201482': 1996.7607440309578,
 '201484': 2002.0907980164438,
 '201489': 2008.704393734016,
 '201492': 1999.4968382414875,
 '201496': 2001.847466319016,
 '2015103': 2014.7751712888405,
 '2015107': 2021.7502594410018,
 '201511': 1977.5244689225794,
 '2015110': 2029.2060814384172,
 '2015114': 2032.1953718102966,
 '2015117': 2033.197606463414,
 '201512': 1977.6884631127734,
 '2015121': 2039.7656435911783,
 '2015124': 2041.751879838808,
 '2015129': 2048.4715414635043,
 '2015130': 2052.859790253423,
 '2015137': 2038.0748442977354,
 '2015139': 2038.9847636215052,
 '2015144': 2044.6362117347946,
 '2015146': 2048.3692012590654,
 '201515': 1978.3238969993856,
 '2015152': 2056.4427741872732,
 '2015154': 2063.5897434075287,
 '201518': 1987.3388844056526,
 '201519': 1990.0929549600144,
 '201523': 1994.6461439275786,
 '201527': 1994.8934227789382,
 '201530': 1995.5816151821355,
 '201542': 2004.4800711547255,
 '201545': 2005.3158540879274,
 '201556': 2012.603410280443,
 '201558': 2014.1723366305057,
 '201561': 2015.2131497665025,
 '201565': 2016.7259766526051,
 '201569': 2018.748396487065,
 '201571': 2003.3909045024993,
 '201575': 1987.846694071122,
 '201577': 1998.8469273333267,
 '201583': 2004.6191351411749,
 '201586': 2008.6005573615432,
 '201589': 1993.9585304855395,
 '201593': 2003.2970901895603,
 '201596': 2005.4513988441263,
 '201598': 2011.051383595451,
 '2016103': 2026.3991259025606,
 '2016107': 2035.5426653355457,
 '201611': 2073.3685719400733,
 '2016110': 2043.4732290890938,
 '2016115': 2031.559916768565,
 '2016118': 2034.9439044122037,
 '201612': 2073.6993704198744,
 '2016120': 2019.5395747204811,
 '2016124': 2021.3158800313713,
 '2016128': 2009.7268528349568,
 '2016129': 2013.7595497434233,
 '2016136': 2000.1269824600718,
 '2016138': 2001.755346933995,
 '2016143': 2003.7988344911228,
 '201615': 2074.0701404301203,
 '201618': 2064.2796491256377,
 '201620': 2068.5341741912903,
 '201623': 2072.5185652575174,
 '201627': 2073.4125717152133,
 '201630': 2074.8955828802455,
 '201633': 2077.7621138678464,
 '201643': 2079.027147258235,
 '201647': 2079.431434261539,
 '201656': 2062.8692533560975,
 '201658': 2063.4925530579594,
 '201661': 2064.4857780117222,
 '201665': 2065.6813136948535,
 '201668': 2067.6292231908646,
 '201672': 2068.642105085901,
 '201675': 2051.070341969441,
 '201677': 2036.4531344660174,
 '201682': 2021.3899053631965,
 '201684': 2025.5433779620726,
 '201692': 2010.7669467189749,
 '201696': 2013.151126928122,
 '201698': 2017.173504761322,
 'temp': 1991.7870110701658}

In [87]:
def elo_timeseries (Team_Id):
    
    #Create a DF from the keys and values of the Dict
    df_team=pd.DataFrame(data= list(Ratings[Team_Id].values()), index=(Ratings[Team_Id].keys()), columns= ['ELO'])
    
    #'Temp', from the way the csv data are put in, is the final 2016 tourney ELO -no more updates-, so move it at the end
    val='temp'
    idx=df_team.index.drop('temp').tolist() + [val]
    df_final=df_team.reindex(idx)
    
    #rename 'Temp' to a 'timestamp'
    last=df_final.index[-1]
    df_final=df_final.rename(index={last:'2016160'})
    
    #add '0' to certain timestamps so they can be sorted properly, this way for eg. 1985026 < 1985100
    #instead of 198526 > 1985100 that was before
    idx2=[]
    for index in df_final.index:
        if len(index) == 6:
            index=index[:4] + '0' + index[4:]
            idx2.append(index)
        elif len(index) == 5:
            index=index[:4] + '00' + index[4:]
            idx2.append(index)
        else:
            idx2.append(index)
    
    #use the timestamps as DF indices and sort
    df_final.index=idx2
    df_final=df_final.sort_index(ascending=True)
    
    return df_final

In [88]:
duke = elo_timeseries(1181)

In [9]:
import matplotlib.pyplot as plt
duke.plot()
plt.show()

In [10]:
type(duke)

pandas.core.frame.DataFrame

In [11]:
duke.to_csv('duke_new.csv')

In [12]:
len(duke)

501

In [56]:
data_path = "trailing_avg_diff_V2.csv"
dataframe = pd.read_csv(data_path, header=0, index_col = 0)

In [57]:
dataframe['Wloc'].replace(to_replace=['H', 'A', 'N'], value=['0', '1', '2'], inplace=True)

In [58]:
d1 = dataframe.loc[dataframe['team1'] == 1181]
d2 = dataframe.loc[dataframe['team2'] == 1181]
dataset = pd.concat([d1, d2])
dataset.reset_index(inplace=True)
dataset.sort_values(by = ['Season', 'Daynum'], inplace=True)
dataset

,Season,Daynum,team1,team2,Wloc,Numot,score_diff,fgm_diff,fga_diff,fgm3_diff,...,ftm_diff,fta_diff,or_diff,dr_diff,ast_diff,to_diff,stl_diff,blk_diff,pf_diff,WorL
412,2003,19,1119,1181,0,0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
413,2003,21,1172,1181,0,0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
0,2003,26,1181,1417,2,0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1
1,2003,29,1181,1326,2,0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1
2,2003,33,1181,1276,0,0,0.139954,0.115156,-0.015437,0.077778,...,0.174603,0.028879,-0.081987,0.187778,0.243534,-0.223754,0.139683,0.033333,0.053333,1
3,2003,43,1181,1299,2,0,0.368584,0.274471,0.072090,0.136508,...,0.496732,0.370083,0.158593,0.202299,0.504023,-0.575000,0.339733,0.652237,-0.307870,1
414,2003,55,1173,1181,0,0,0.147593,0.069444,-0.146809,0.157828,...,0.289409,0.210459,-0.792929,0.055797,0.225371,-0.391946,0.175926,0.600000,-0.124638,0
4,2003,59,1181,1193,0,0,0.243356,0.201905,0.089286,0.531481,...,0.079772,-0.097436,0.088889,0.064394,0.361111,-0.329437,0.232540,0.161111,-0.152515,1
415,2003,62,1155,1181,1,0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
5,2003,65,1181,1207,0,0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1
6,2003,69,1181,1448,0,0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1
7,2003,72,1181,1438,0,0,0.115665,-0.076235,-0.162077,0.095238,...,0.480735,0.378621,-0.513889,0.108783,0.146011,-0.142157,-0.050000,0.055556,-0.339425,1
8,2003,75,1181,1268,0,0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
9,2003,79,1181,1301,0,0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
10,2003,82,1181,1210,0,0,0.161608,0.118829,-0.048036,-0.014286,...,0.184603,0.128426,-0.080556,0.228219,0.166667,-0.234932,-0.583333,0.189815,-0.171118,1
416,2003,87,1139,1181,0,0,0.113547,0.106101,0.054726,-0.946032,...,0.431602,0.421958,0.365599,0.165237,0.113131,-0.133333,-1.323810,0.383333,-0.534853,0
11,2003,90,1181,1199,0,0,0.115785,0.070739,-0.251916,-0.764286,...,0.350427,0.258739,-0.687678,0.295088,0.111734,0.089978,-0.219048,0.509524,-0.292504,0
12,2003,93,1181,1314,0,0,0.127287,0.101970,-0.048943,-0.516667,...,0.321988,0.197724,0.203237,0.327098,-0.007867,0.190731,-0.323232,0.060317,-0.089234,1
417,2003,97,1155,1181,0,0,0.228698,0.144833,0.074188,0.211111,...,0.128037,-0.039152,0.071429,0.032454,0.303590,-0.445496,0.238636,0.166667,-0.191729,0
13,2003,101,1181,1448,0,2,0.108090,0.178763,-0.264474,-0.966667,...,0.139316,0.160823,-0.745370,0.327495,0.192752,0.177037,-0.952381,0.422222,-0.288745,0
14,2003,103,1181,1438,1,0,0.219384,0.194904,0.018270,0.104798,...,0.246561,0.245000,-0.127578,0.069295,0.192857,-0.376374,0.403788,0.309524,-0.306878,1
15,2003,107,1181,1268,0,0,0.074559,0.003708,-0.184920,0.114316,...,0.116734,0.196795,-0.366165,0.209770,-0.128205,0.134127,-0.377778,0.190476,-0.153604,1
16,2003,110,1181,1301,0,0,0.157200,0.083209,0.097117,0.119048,...,0.319968,0.280719,0.123529,-0.107937,0.065954,-0.645788,0.342857,0.177778,-0.146825,1
17,2003,114,1181,1210,1,0,0.148692,0.169355,-0.154629,-0.150000,...,-0.165344,0.108814,-0.353846,0.291667,0.180687,0.158789,0.158730,0.277778,-0.078431,1
18,2003,118,1181,1385,0,0,0.075619,0.137097,-0.124882,-1.333333,...,0.189433,0.170346,-0.302189,0.249573,0.008929,-0.097037,-0.638095,0.088889,-0.181366,0
19,2003,122,1181,1199,0,0,0.157140,0.041818,-0.067291,0.065476,...,0.447460,0.287704,-0.115419,0.240079,-0.047890,-0.002597,-0.414835,0.182540,-0.110571,1
20,2003,125,1181,1314,0,0,0.065737,0.093137,-0.047758,-0.535714,...,0.086869,0.085119,-0.098485,0.179233,0.156798,-0.100741,-0.900000,0.031746,-0.200665,0
21,2003,130,1181,1438,2,0,0.153112,0.089246,-0.060096,0.016667,...,0.337186,0.194444,-0.464646,-0.023316,0.122473,-0.250754,0.218182,-0.162963,-0.311111,1
22,2003,131,1181,1314,2,0,0.153509,0.089286,0.000584,-0.171296,...,0.393582,0.258630,0.150427,0.228700,0.118709,-0.082479,0.248148,-0.007937,-0.319088,1
23,2003,132,1181,1301,2,0,0.067260,0.047604,0.006410,-0.055556,...,0.083333,0.209320,0.101732,0.040000,0.085901,-0.140693,0.259259,0.344444,-0.027609,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
358,2016,27,1181,1429,0,0,0.159641,0.221983,0.042249,-0.592593,...,0.119192,0.135234,0.061002,0.176331,0.284314,-0.158333,0.233333,0.259259,-0.118170,1
359,2016,30,1181,1231,0,0,0.099938,0.206767,0.171056,-0.246032,...,-0.581746,-0.407204,0.350080,0.046923,-0.455698,-0.318071,-0.142857,-0.722222,0.036062,1
483,2016,33,1138,1181,0,0,0.184780,0.197340,0.031474,0.063492,...,-0.120539,-0.515058,-0.195960,0.008305,0.285881,-0.484944,0.037037,0.388889,-0.246590,0
360,2016,43,1181,1204,0,0,0.169655,0.177937,-0.081618,0.291866,...,-0.142484,-0.172788,-0.786232,0.128205,0.317460,0.043981,-0.441667,0.430556,-0.286995,1
361,2016,47,1181,1428,2,1,0.101880,0.117852,-0.080999,-0.694444,...,0.081426,-0.030027,-0.367725,0.130105,0.314076,-0.060606,-0.313889,0.091667,0.027497,0
362,2016,56,1181,1189,0,0,0.192872,0.181602,-0.058240,-0.347375,...,0.309174,0.133578,-0.203083,0.303333,-0.072090,-0.074495,0.183333,0.678571,-0.127564,1
363,2016,58,1181,1253,0,0,0.202337,0.040808,-0.024832,0.011111,...,0.570215,0.389899,0.066667,0.238365,-0.000975,-0.488248,0.111905,0.416667,-0.424464,1
484,2016,61,1130,1181,1,0,0.153394,0.064755,-0.065065,-0.042593,...,0.385931,0.377171,-0.056878,0.165972,0.088889,-0.088989,0.140152,0.111111,-0.431849,0
364,2016,65,1181,1448,1,0,0.132130,0.097647,-0.059133,-0.055556,...,0.331169,0.139272,-0.371044,0.141629,-0.639286,-0.208791,0.083333,-1.338624,-0.104598,1
365,2016,68,1181,1439,0,0,0.260852,0.219191,0.149304,0.548148,...,0.206522,0.201974,0.437799,0.217374,0.400735,-0.187831,0.384848,0.088889,-0.234893,1
485,2016,72,1155,1181,0,0,0.081590,0.143493,0.008170,-0.821429,...,0.120445,-0.028195,0.147427,0.204179,0.221814,-0.025641,-0.207407,0.341667,0.062356,1
366,2016,75,1181,1323,1,0,0.046590,0.120534,0.017504,-0.863095,...,0.105739,-0.099206,0.208429,0.233165,0.025385,0.017216,-0.296296,0.216667,0.144426,0
367,2016,77,1181,1393,1,0,0.048300,0.088704,0.138536,-0.418651,...,-0.091629,-0.052910,0.378623,0.060185,-0.092262,-0.253154,0.314815,-0.583333,0.035784,0
368,2016,82,1181,1301,1,0,0.123408,0.121479,0.038589,0.182828,...,0.061538,0.092792,-0.042424,0.036476,0.035453,-0.276190,0.081481,0.472222,-0.019022,1
369,2016,84,1181,1274,0,0,0.069413,0.142468,0.109170,-0.138889,...,-0.348039,-0.195767,0.057916,0.000604,0.141905,-0.394180,0.166667,-0.541667,0.133824,0
370,2016,92,1181,1210,1,0,0.070974,0.001232,-0.102456,0.392857,...,0.110806,0.224206,-0.287879,-0.081638,0.116071,-0.116883,-0.083333,0.044444,-0.166667,1
371,2016,96,1181,1301,0,0,0.072698,-0.030518,-0.073383,0.100000,...,0.164444,0.184885,-0.162500,0.057987,0.225000,-0.100000,0.041667,0.305556,-0.190807,1
372,2016,98,1181,1257,0,0,0.135197,-0.159371,-0.301713,0.331746,...,0.140693,0.247115,-1.055556,0.034493,0.086364,-0.143086,-0.059259,-0.125000,-0.370760,1
373,2016,103,1181,1438,0,0,0.057865,-0.043485,-0.129620,0.417989,...,0.103263,0.202882,0.179293,0.223194,-0.222222,0.282576,0.083333,0.300000,-0.253968,1
374,2016,107,1181,1314,1,0,0.048683,-0.017196,0.020502,0.111111,...,0.002282,0.043695,-0.135913,-0.127646,-0.657692,-1.368056,0.510823,-0.388889,-0.210726,1
375,2016,110,1181,1257,0,0,0.087931,0.159864,0.088743,-0.073413,...,-0.383333,-0.037037,0.015432,0.000604,0.324444,-0.398148,0.166667,-0.125000,0.066904,0
376,2016,115,1181,1199,0,0,0.124399,0.057471,0.011996,0.411111,...,0.172348,0.246544,0.043305,-0.077922,0.271242,-0.505051,-0.496212,-0.244444,-0.250794,1
377,2016,118,1181,1338,0,0,0.138281,0.249166,0.093860,-0.212302,...,-0.210256,-0.020833,0.093137,0.153382,0.483175,-0.338889,-0.111111,0.541667,0.155793,0
378,2016,120,1181,1448,0,0,0.114170,-0.041709,-0.079950,0.162037,...,0.401937,0.305538,-0.248148,-0.031781,-0.186508,-0.353276,0.236208,-0.174603,-0.183829,1
379,2016,124,1181,1314,1,0,0.110329,0.207748,0.126442,-0.853968,...,-0.035653,0.090278,0.458217,0.279240,0.353175,0.005556,-0.388889,0.250000,0.030303,0
380,2016,128,1181,1301,2,0,0.102078,0.040804,-0.070289,0.410256,...,0.043056,0.072733,-0.343434,0.044022,0.343860,-0.096296,-0.013889,0.512698,0.007393,1
381,2016,129,1181,1323,2,1,0.097530,0.181052,0.002772,-0.877778,...,0.079162,0.090278,0.256828,0.401462,0.297619,0.322807,-0.833333,0.083333,-0.060606,0
409,2016,136,1181,1423,2,0,0.101245,-0.132323,-0.214478,-0.436364,...,0.631143,0.609626,0.079622,0.244349,-0.372222,0.176136,-0.217460,0.451852,-0.772962,1
410,2016,138,1181,1463,2,0,0.143010,0.010684,-0.128567,0.387037,...,0.298441,0.248800,-1.177778,0.065035,-0.055271,-0.213636,0.230952,0.285714,-0.101215,1
411,2016,143,1181,1332,2,0,0.093149,0.126715,-0.013708,-0.675758,...,0.119048,0.148148,0.259844,0.294831,0.283816,0.300585,-0.694444,0.194444,-0.164310,0

In [59]:
dataset[dataset['Daynum'] == 4]

,Season,Daynum,team1,team2,Wloc,Numot,score_diff,fgm_diff,fga_diff,fgm3_diff,...,ftm_diff,fta_diff,or_diff,dr_diff,ast_diff,to_diff,stl_diff,blk_diff,pf_diff,WorL
131,2008,4,1181,1300,0,0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1
270,2013,4,1181,1209,0,0,0.120450,0.180864,0.101943,-0.007937,...,-0.354167,-0.411538,0.062271,0.039309,0.026455,-0.243056,-0.157265,0.033862,0.120290,1
472,2014,4,1172,1181,0,0,0.167779,0.192511,-0.020688,-0.173016,...,0.163690,0.163564,-0.759259,0.193086,-0.214201,-0.466667,0.641667,0.476190,-0.085248,0

In [60]:
if(len(str(dataset['Daynum'])) == 2):
    dataset['index'] = dataset['Season'].astype('str') + '0' + dataset['Daynum'].astype('str')
else:
    dataset['index'] = dataset['Season'].astype('str') + dataset['Daynum'].astype('str')

In [61]:
dataset['index']

412     200319
413     200321
0       200326
1       200329
2       200333
3       200343
414     200355
4       200359
415     200362
5       200365
6       200369
7       200372
8       200375
9       200379
10      200382
416     200387
11      200390
12      200393
417     200397
13     2003101
14     2003103
15     2003107
16     2003110
17     2003114
18     2003118
19     2003122
20     2003125
21     2003130
22     2003131
23     2003132
        ...
358     201627
359     201630
483     201633
360     201643
361     201647
362     201656
363     201658
484     201661
364     201665
365     201668
485     201672
366     201675
367     201677
368     201682
369     201684
370     201692
371     201696
372     201698
373    2016103
374    2016107
375    2016110
376    2016115
377    2016118
378    2016120
379    2016124
380    2016128
381    2016129
409    2016136
410    2016138
411    2016143
Name: index, dtype: object

In [76]:
def update_index(x):
    x = str(x)
    if(len(x) == 5):
        x=x[:4] + '00' + x[4:]
    elif(len(x) == 6):
        x=x[:4] + '0' + x[4:]
        
    return(x)

In [77]:
print(update_index('20034'))

2003004

In [78]:
dataset['index'] = dataset['index'].apply(update_index)
dataset['index']

412    2003019
413    2003021
0      2003026
1      2003029
2      2003033
3      2003043
414    2003055
4      2003059
415    2003062
5      2003065
6      2003069
7      2003072
8      2003075
9      2003079
10     2003082
416    2003087
11     2003090
12     2003093
417    2003097
13     2003101
14     2003103
15     2003107
16     2003110
17     2003114
18     2003118
19     2003122
20     2003125
21     2003130
22     2003131
23     2003132
        ...
358    2016027
359    2016030
483    2016033
360    2016043
361    2016047
362    2016056
363    2016058
484    2016061
364    2016065
365    2016068
485    2016072
366    2016075
367    2016077
368    2016082
369    2016084
370    2016092
371    2016096
372    2016098
373    2016103
374    2016107
375    2016110
376    2016115
377    2016118
378    2016120
379    2016124
380    2016128
381    2016129
409    2016136
410    2016138
411    2016143
Name: index, dtype: object

In [79]:
dataset.columns

Index(['Season', 'Daynum', 'team1', 'team2', 'Wloc', 'Numot', 'score_diff',
       'fgm_diff', 'fga_diff', 'fgm3_diff', 'fga3_diff', 'ftm_diff',
       'fta_diff', 'or_diff', 'dr_diff', 'ast_diff', 'to_diff', 'stl_diff',
       'blk_diff', 'pf_diff', 'WorL', 'index'],
      dtype='object')

In [80]:
dataset.set_index('index', inplace=True)
dataset[:5]

,Season,Daynum,team1,team2,Wloc,Numot,score_diff,fgm_diff,fga_diff,fgm3_diff,...,ftm_diff,fta_diff,or_diff,dr_diff,ast_diff,to_diff,stl_diff,blk_diff,pf_diff,WorL
index,,,,,,,,,,,,,,,,,,,,,
2003019,2003,19,1119,1181,0,0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
2003021,2003,21,1172,1181,0,0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
2003026,2003,26,1181,1417,2,0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1
2003029,2003,29,1181,1326,2,0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1
2003033,2003,33,1181,1276,0,0,0.139954,0.115156,-0.015437,0.077778,...,0.174603,0.028879,-0.081987,0.187778,0.243534,-0.223754,0.139683,0.033333,0.053333,1

In [90]:
duke_new = duke[:-1]
len(duke_new)

500

In [91]:
print(duke_new.index.tolist())

['2003019', '2003021', '2003026', '2003029', '2003033', '2003043', '2003055', '2003059', '2003062', '2003065', '2003069', '2003072', '2003075', '2003079', '2003082', '2003087', '2003090', '2003093', '2003097', '2003101', '2003103', '2003107', '2003110', '2003114', '2003118', '2003122', '2003125', '2003130', '2003131', '2003132', '2003136', '2003138', '2003143', '2004019', '2004024', '2004025', '2004026', '2004030', '2004033', '2004041', '2004044', '2004047', '2004056', '2004061', '2004064', '2004069', '2004073', '2004075', '2004079', '2004082', '2004087', '2004089', '2004094', '2004097', '2004100', '2004104', '2004107', '2004111', '2004115', '2004118', '2004121', '2004124', '2004130', '2004131', '2004132', '2004136', '2004138', '2004144', '2004146', '2004152', '2005019', '2005021', '2005026', '2005029', '2005033', '2005041', '2005043', '2005047', '2005062', '2005065', '2005068', '2005073', '2005076', '2005079', '2005082', '2005086', '2005090', '2005093', '2005096', '2005100', '2005103', '2005108', '2005111', '2005114', '2005117', '2005122', '2005125', '2005130', '2005131', '2005132', '2005137', '2005139', '2005144', '2006014', '2006016', '2006019', '2006023', '2006025', '2006030', '2006034', '2006037', '2006040', '2006048', '2006051', '2006061', '2006063', '2006069', '2006072', '2006075', '2006079', '2006082', '2006087', '2006089', '2006093', '2006096', '2006099', '2006103', '2006106', '2006111', '2006114', '2006117', '2006121', '2006124', '2006130', '2006131', '2006132', '2006136', '2006138', '2006143', '2007013', '2007014', '2007017', '2007021', '2007022', '2007026', '2007029', '2007033', '2007037', '2007040', '2007050', '2007052', '2007062', '2007064', '2007068', '2007072', '2007076', '2007080', '2007082', '2007087', '2007090', '2007094', '2007097', '2007100', '2007104', '2007107', '2007111', '2007115', '2007118', '2007121', '2007125', '2007129', '2007136', '2008004', '2008007', '2008014', '2008015', '2008016', '2008020', '2008022', '2008026', '2008033', '2008042', '2008045', '2008062', '2008065', '2008069', '2008072', '2008075', '2008080', '2008083', '2008087', '2008089', '2008093', '2008096', '2008100', '2008104', '2008107', '2008110', '2008114', '2008117', '2008121', '2008124', '2008130', '2008131', '2008136', '2008138', '2009007', '2009008', '2009013', '2009017', '2009018', '2009020', '2009025', '2009029', '2009033', '2009044', '2009047', '2009058', '2009062', '2009065', '2009068', '2009072', '2009075', '2009078', '2009082', '2009086', '2009090', '2009093', '2009096', '2009100', '2009104', '2009108', '2009111', '2009114', '2009117', '2009120', '2009125', '2009130', '2009131', '2009132', '2009136', '2009138', '2009143', '2010011', '2010014', '2010015', '2010019', '2010023', '2010025', '2010030', '2010033', '2010043', '2010047', '2010057', '2010059', '2010062', '2010065', '2010068', '2010072', '2010076', '2010079', '2010082', '2010086', '2010089', '2010094', '2010096', '2010100', '2010103', '2010107', '2010111', '2010115', '2010118', '2010121', '2010124', '2010130', '2010131', '2010132', '2010137', '2010139', '2010144', '2010146', '2010152', '2010154', '2011013', '2011015', '2011018', '2011021', '2011022', '2011026', '2011030', '2011033', '2011037', '2011040', '2011049', '2011058', '2011062', '2011065', '2011069', '2011072', '2011075', '2011079', '2011082', '2011087', '2011090', '2011093', '2011096', '2011100', '2011104', '2011107', '2011111', '2011114', '2011117', '2011121', '2011124', '2011130', '2011131', '2011132', '2011137', '2011139', '2011143', '2012011', '2012012', '2012015', '2012018', '2012021', '2012022', '2012023', '2012029', '2012037', '2012040', '2012049', '2012060', '2012062', '2012065', '2012068', '2012073', '2012076', '2012080', '2012082', '2012086', '2012089', '2012094', '2012097', '2012100', '2012103', '2012108', '2012111', '2012115', '2012117', '2012120', '2012124', '2012130', '2012131', '2012137', '2013004', '2013008', '2013013', '2013017', '2013018', '2013019', '2013023', '2013026', '2013033', '2013044', '2013045', '2013054', '2013058', '2013061', '2013064', '2013068', '2013073', '2013079', '2013082', '2013086', '2013089', '2013094', '2013097', '2013100', '2013103', '2013108', '2013111', '2013115', '2013117', '2013120', '2013124', '2013130', '2013137', '2013139', '2013144', '2013146', '2014004', '2014008', '2014011', '2014014', '2014015', '2014020', '2014023', '2014025', '2014029', '2014042', '2014045', '2014054', '2014057', '2014061', '2014064', '2014068', '2014070', '2014075', '2014079', '2014082', '2014084', '2014089', '2014092', '2014096', '2014103', '2014106', '2014108', '2014110', '2014113', '2014121', '2014124', '2014130', '2014131', '2014132', '2014137', '2015011', '2015012', '2015015', '2015018', '2015019', '2015023', '2015027', '2015030', '2015042', '2015045', '2015056', '2015058', '2015061', '2015065', '2015069', '2015071', '2015075', '2015077', '2015083', '2015086', '2015089', '2015093', '2015096', '2015098', '2015103', '2015107', '2015110', '2015114', '2015117', '2015121', '2015124', '2015129', '2015130', '2015137', '2015139', '2015144', '2015146', '2015152', '2015154', '2016011', '2016012', '2016015', '2016018', '2016020', '2016023', '2016027', '2016030', '2016033', '2016043', '2016047', '2016056', '2016058', '2016061', '2016065', '2016068', '2016072', '2016075', '2016077', '2016082', '2016084', '2016092', '2016096', '2016098', '2016103', '2016107', '2016110', '2016115', '2016118', '2016120', '2016124', '2016128', '2016129', '2016136', '2016138', '2016143']

In [92]:
print(dataset.index.tolist())

['2003019', '2003021', '2003026', '2003029', '2003033', '2003043', '2003055', '2003059', '2003062', '2003065', '2003069', '2003072', '2003075', '2003079', '2003082', '2003087', '2003090', '2003093', '2003097', '2003101', '2003103', '2003107', '2003110', '2003114', '2003118', '2003122', '2003125', '2003130', '2003131', '2003132', '2003136', '2003138', '2003143', '2004019', '2004024', '2004025', '2004026', '2004030', '2004033', '2004041', '2004044', '2004047', '2004056', '2004061', '2004064', '2004069', '2004073', '2004075', '2004079', '2004082', '2004087', '2004089', '2004094', '2004097', '2004100', '2004104', '2004107', '2004111', '2004115', '2004118', '2004121', '2004124', '2004130', '2004131', '2004132', '2004136', '2004138', '2004144', '2004146', '2004152', '2005019', '2005021', '2005026', '2005029', '2005033', '2005041', '2005043', '2005047', '2005062', '2005065', '2005068', '2005073', '2005076', '2005079', '2005082', '2005086', '2005090', '2005093', '2005096', '2005100', '2005103', '2005108', '2005111', '2005114', '2005117', '2005122', '2005125', '2005130', '2005131', '2005132', '2005137', '2005139', '2005144', '2006014', '2006016', '2006019', '2006023', '2006025', '2006030', '2006034', '2006037', '2006040', '2006048', '2006051', '2006061', '2006063', '2006069', '2006072', '2006075', '2006079', '2006082', '2006087', '2006089', '2006093', '2006096', '2006099', '2006103', '2006106', '2006111', '2006114', '2006117', '2006121', '2006124', '2006130', '2006131', '2006132', '2006136', '2006138', '2006143', '2007013', '2007014', '2007017', '2007021', '2007022', '2007026', '2007029', '2007033', '2007037', '2007040', '2007050', '2007052', '2007062', '2007064', '2007068', '2007072', '2007076', '2007080', '2007082', '2007087', '2007090', '2007094', '2007097', '2007100', '2007104', '2007107', '2007111', '2007115', '2007118', '2007121', '2007125', '2007129', '2007136', '2008004', '2008007', '2008014', '2008015', '2008016', '2008020', '2008022', '2008026', '2008033', '2008042', '2008045', '2008062', '2008065', '2008069', '2008072', '2008075', '2008080', '2008083', '2008087', '2008089', '2008093', '2008096', '2008100', '2008104', '2008107', '2008110', '2008114', '2008117', '2008121', '2008124', '2008130', '2008131', '2008136', '2008138', '2009007', '2009008', '2009013', '2009017', '2009018', '2009020', '2009025', '2009029', '2009033', '2009044', '2009047', '2009058', '2009062', '2009065', '2009068', '2009072', '2009075', '2009078', '2009082', '2009086', '2009090', '2009093', '2009096', '2009100', '2009104', '2009108', '2009111', '2009114', '2009117', '2009120', '2009125', '2009130', '2009131', '2009132', '2009136', '2009138', '2009143', '2010011', '2010014', '2010015', '2010019', '2010023', '2010025', '2010030', '2010033', '2010043', '2010047', '2010057', '2010059', '2010062', '2010065', '2010068', '2010072', '2010076', '2010079', '2010082', '2010086', '2010089', '2010094', '2010096', '2010100', '2010103', '2010107', '2010111', '2010115', '2010118', '2010121', '2010124', '2010130', '2010131', '2010132', '2010137', '2010139', '2010144', '2010146', '2010152', '2010154', '2011013', '2011015', '2011018', '2011021', '2011022', '2011026', '2011030', '2011033', '2011037', '2011040', '2011049', '2011058', '2011062', '2011065', '2011069', '2011072', '2011075', '2011079', '2011082', '2011087', '2011090', '2011093', '2011096', '2011100', '2011104', '2011107', '2011111', '2011114', '2011117', '2011121', '2011124', '2011130', '2011131', '2011132', '2011137', '2011139', '2011143', '2012011', '2012012', '2012015', '2012018', '2012021', '2012022', '2012023', '2012029', '2012037', '2012040', '2012049', '2012060', '2012062', '2012065', '2012068', '2012073', '2012076', '2012080', '2012082', '2012086', '2012089', '2012094', '2012097', '2012100', '2012103', '2012108', '2012111', '2012115', '2012117', '2012120', '2012124', '2012130', '2012131', '2012137', '2013004', '2013008', '2013013', '2013017', '2013018', '2013019', '2013023', '2013026', '2013033', '2013044', '2013045', '2013054', '2013058', '2013061', '2013064', '2013068', '2013073', '2013079', '2013082', '2013086', '2013089', '2013094', '2013097', '2013100', '2013103', '2013108', '2013111', '2013115', '2013117', '2013120', '2013124', '2013130', '2013137', '2013139', '2013144', '2013146', '2014004', '2014008', '2014011', '2014014', '2014015', '2014020', '2014023', '2014025', '2014029', '2014042', '2014045', '2014054', '2014057', '2014061', '2014064', '2014068', '2014070', '2014075', '2014079', '2014082', '2014084', '2014089', '2014092', '2014096', '2014103', '2014106', '2014108', '2014110', '2014113', '2014121', '2014124', '2014130', '2014131', '2014132', '2014137', '2015011', '2015012', '2015015', '2015018', '2015019', '2015023', '2015027', '2015030', '2015042', '2015045', '2015056', '2015058', '2015061', '2015065', '2015069', '2015071', '2015075', '2015077', '2015083', '2015086', '2015089', '2015093', '2015096', '2015098', '2015103', '2015107', '2015110', '2015114', '2015117', '2015121', '2015124', '2015129', '2015130', '2015137', '2015139', '2015144', '2015146', '2015152', '2015154', '2016011', '2016012', '2016015', '2016018', '2016020', '2016023', '2016027', '2016030', '2016033', '2016043', '2016047', '2016056', '2016058', '2016061', '2016065', '2016068', '2016072', '2016075', '2016077', '2016082', '2016084', '2016092', '2016096', '2016098', '2016103', '2016107', '2016110', '2016115', '2016118', '2016120', '2016124', '2016128', '2016129', '2016136', '2016138', '2016143']

In [93]:
len(set(dataset.index) & set(duke_new.index))

500

In [94]:
dataset.index.tolist() == duke_new.index.tolist()

True

In [100]:
my_data = pd.concat([dataset, duke_new], axis=1, join_axes=[dataset.index])
my_data[:5]

,Season,Daynum,team1,team2,Wloc,Numot,score_diff,fgm_diff,fga_diff,fgm3_diff,...,fta_diff,or_diff,dr_diff,ast_diff,to_diff,stl_diff,blk_diff,pf_diff,WorL,ELO
index,,,,,,,,,,,,,,,,,,,,,
2003019,2003,19,1119,1181,0,0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,1500.000000
2003021,2003,21,1172,1181,0,0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,1510.000000
2003026,2003,26,1181,1417,2,0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1,1519.712256
2003029,2003,29,1181,1326,2,0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1,1528.867370
2003033,2003,33,1181,1276,0,0,0.139954,0.115156,-0.015437,0.077778,...,0.028879,-0.081987,0.187778,0.243534,-0.223754,0.139683,0.033333,0.053333,1,1538.037708

In [99]:
duke_new[:5]

                 ELO
2003019  1500.000000
2003021  1510.000000
2003026  1519.712256
2003029  1528.867370
2003033  1538.037708

In [101]:
cols = my_data.columns.tolist()
cols

['Season',
 'Daynum',
 'team1',
 'team2',
 'Wloc',
 'Numot',
 'score_diff',
 'fgm_diff',
 'fga_diff',
 'fgm3_diff',
 'fga3_diff',
 'ftm_diff',
 'fta_diff',
 'or_diff',
 'dr_diff',
 'ast_diff',
 'to_diff',
 'stl_diff',
 'blk_diff',
 'pf_diff',
 'WorL',
 'ELO']

In [103]:
cols = cols[:-2] + [cols[-1]] + [cols[-2]]
cols

['Season',
 'Daynum',
 'team1',
 'team2',
 'Wloc',
 'Numot',
 'score_diff',
 'fgm_diff',
 'fga_diff',
 'fgm3_diff',
 'fga3_diff',
 'ftm_diff',
 'fta_diff',
 'or_diff',
 'dr_diff',
 'ast_diff',
 'to_diff',
 'stl_diff',
 'blk_diff',
 'pf_diff',
 'ELO',
 'WorL']

In [104]:
my_data = my_data[cols]
my_data[:5]

,Season,Daynum,team1,team2,Wloc,Numot,score_diff,fgm_diff,fga_diff,fgm3_diff,...,fta_diff,or_diff,dr_diff,ast_diff,to_diff,stl_diff,blk_diff,pf_diff,ELO,WorL
index,,,,,,,,,,,,,,,,,,,,,
2003019,2003,19,1119,1181,0,0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1500.000000,0
2003021,2003,21,1172,1181,0,0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1510.000000,0
2003026,2003,26,1181,1417,2,0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1519.712256,1
2003029,2003,29,1181,1326,2,0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1528.867370,1
2003033,2003,33,1181,1276,0,0,0.139954,0.115156,-0.015437,0.077778,...,0.028879,-0.081987,0.187778,0.243534,-0.223754,0.139683,0.033333,0.053333,1538.037708,1

In [105]:
my_data.to_csv('duke-with-ELO.csv')